ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - io.craigmiller160.KtorPracticeRunnerKt.rootModule
      - io.craigmiller160.database.ModuleKt.databaseModule
      - io.craigmiller160.people.ModuleKt.peopleModule

postgres:
  jdbcUrl: $POSTGRES_URL
  username: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  maxPoolSize: $POSTGRES_MAX_POOL_SIZE