ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - io.craigmiller160.KtorPracticeRunner.rootModule
      - io.craigmiller160.plugins.DatabaseKt.databaseModule
      - io.craigmiller160.people.PeopleKt.peopleModule

postgres:
  jdbcUrl: $POSTGRES_URL
  username: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  maxPoolSize: $POSTGRES_MAX_POOL_SIZE